import './normalize.css';
import './index.css';
import ItemSearch from './ItemSearch';

export function App() {
	return (
		<>
			<main>
				<ItemSearch></ItemSearch>
			</main>
			<footer>
				<hr />
				<p className='important-footer'>Contact: szdytom[at]qq.com. If you have suggestions, feedbacks or anything that else want to share with me, please feel free to send an email.</p>
				<p className='important-footer'>This website and related scripts is <a target='_blank' href='https://github.com/szdytom/infinite-autocraft'>open-source on GitHub</a>, please give me star if liked it.</p>
				<p>This website is not owned or operated by <a target='_blank' href='https://neal.fun/'>neal.fun</a>, nor does it represent the official opinions of <a href='https://neal.fun/'>neal.fun</a>.</p>
				<p>The content of the website is mostly collected and organized from the game <a target='_blank' href='https://neal.fun/infinite-craft/'>Infinite Craft</a>, and the crafting recipes are generated by AI. It may contain some discriminatory or offensive viewpoints, which do not represent the views supported by the website operator nor Github Pages. If you feel uncomfortable, please close this website.</p>
				<p>This website does not use cookies.</p>
			</footer>
		</>
	)
}
